---------------------------- MODULE LeGIT_AI ----------------------------
(*
 * LeGIT/AI Tool Architecture - TLA+ Formal Specification
 * Source: CS486C Senior Capstone Design Project Description [cite: 1, 2]
 * "LeGIT/AI (Logical expression Generator Intended for TLA+
 * with Artificial Intelligence)" [cite: 3]
 *
 * Overview (Source: Project Overview):
 * This technical specification models the state architecture of a VS Code
 * automation tool. The tool translates informal natural language requirements
 * from NVMe and PCIe Standard PDFs into formal TLA+ specifications using AI. [cite: 10, 14, 15]
 *
 * Key concepts modeled
 * - Inputs: Loaded PDF file, Extracted natural language context [cite: 11, 14]
 * - AI Processing: Effective prompt generation, GitHub Copilot draft generation [cite: 15, 21]
 * - Workflow state: User manual edits, iterative TLC model checking [cite: 16, 17]
 * - Outputs: Global dictionary of VARIABLES and CONSTANTS [cite: 19, 20]
 *
 * State-space sizing:
 * Models the lifecycle of a single feature extraction. Highly bounded state
 * space easily verified by exhaustive TLC limits. [cite: 23]
 *)

EXTENDS Naturals, Sequences, FiniteSets, Strings

(* ================================================================
 * CONSTANTS
 * ================================================================ *)

CONSTANTS
    Features,        (* Set of all possible NVMe/PCIe features to extract *)
    EmptyString,     (* Represents an empty text buffer *)
    NullFeature      (* Sentinel value for no feature selected *)

(* ----------------------------------------------------------------
 * Well-formedness assumptions on constants
 * ---------------------------------------------------------------- *)
ASSUME EmptyString \in STRING
ASSUME NullFeature \notin Features

(* ================================================================
 * NAMED CONSTANTS (result codes)
 * ================================================================ *)

(*
 * TLC Model Checker Result Codes
 * Source: Derived from the "Pass TLC?" decision block. [cite: 24]
 *)
TLC_Pending == "Pending"
TLC_Pass    == "Pass"
TLC_Fail    == "Fail"

(* ================================================================
 * STATE VARIABLES
 * ================================================================ *)

VARIABLES
    loadedPDF,       (* loadedPDF : STRING - NVMe or PCIe Standard Spec PDF [cite: 14] *)
    activeFeature,   (* activeFeature : Features \cup {NullFeature} - Target feature *)
    extractedContext,(* extractedContext : STRING
                        Relevant context extracted from the large block of
                        requirement text. [cite: 11] *)
    agentPrompt,     (* agentPrompt : STRING
                        Effective prompt for the Agent mode AI. [cite: 21] *)
    draftTLA_File,   (* draftTLA_File : STRING
                        Draft TLA+ specification file generated by AI or
                        manually edited by user. [cite: 15, 16] *)
    tlcStatus,       (* tlcStatus : ResultCode
                        Holds the verification status of the current draft. [cite: 17, 18] *)
    globalDictionary (* globalDictionary : SUBSET STRING
                        A dictionary of the VARIABLES and CONSTANTS found
                        in the successfully model-checked specification. [cite: 19] *)

vars == <<loadedPDF, activeFeature, extractedContext, agentPrompt, 
          draftTLA_File, tlcStatus, globalDictionary>>

(* ================================================================
 * HELPER DEFINITIONS
 * ================================================================ *)

TLC_ResultCodes == {TLC_Pending, TLC_Pass, TLC_Fail}

(*
 * HasPendingVerification - TRUE iff the tool has a draft that has
 * not yet been successfully passed through the TLC model checker.
 *)
HasPendingVerification == 
    draftTLA_File # EmptyString /\ tlcStatus # TLC_Pass

(* ================================================================
 * TYPE INVARIANT
 * ================================================================ *)

TypeOK ==
    /\ loadedPDF        \in STRING
    /\ activeFeature    \in Features \cup {NullFeature}
    /\ extractedContext \in STRING
    /\ agentPrompt      \in STRING
    /\ draftTLA_File    \in STRING
    /\ tlcStatus        \in TLC_ResultCodes
    /\ globalDictionary \in SUBSET STRING

(* ================================================================
 * INITIAL STATE
 * ================================================================ *)

(*
 * Source (Project Overview):
 * At startup, the IDE extension is initialized with empty buffers
 * and no selected features or pending verification states.
 *)
Init ==
    /\ loadedPDF        = EmptyString
    /\ activeFeature    = NullFeature
    /\ extractedContext = EmptyString
    /\ agentPrompt      = EmptyString
    /\ draftTLA_File    = EmptyString
    /\ tlcStatus        = TLC_Pending
    /\ globalDictionary = {}

(* ================================================================
 * ACTIONS
 * ================================================================ *)

(* ----------------------------------------------------------------
 * Load_PDF_Specification(pdfName)
 *
 * Source (section Project Overview):
 * "The requirements will be provided in the form of NVMe and PCIe
 * Standard Specification PDF files." [cite: 14]
 *)
Load_PDF_Specification(pdfName) ==
    /\ loadedPDF' = pdfName
    /\ UNCHANGED <<activeFeature, extractedContext, agentPrompt, 
                   draftTLA_File, tlcStatus, globalDictionary>>

(* ----------------------------------------------------------------
 * Extract_Feature_Context(feature, contextText)
 *
 * Source (section Project Overview):
 * "extract the relevant context for a specific feature" [cite: 11]
 *)
Extract_Feature_Context(feature, contextText) ==
    /\ loadedPDF # EmptyString
    /\ activeFeature' = feature
    /\ extractedContext' = contextText
    /\ UNCHANGED <<loadedPDF, agentPrompt, draftTLA_File, 
                   tlcStatus, globalDictionary>>

(* ----------------------------------------------------------------
 * Generate_AI_Prompt(promptText)
 *
 * Source (section Project Overview):
 * "provide effective prompt for the Agent mode AI." [cite: 21]
 *)
Generate_AI_Prompt(promptText) ==
    /\ extractedContext # EmptyString
    /\ agentPrompt' = promptText
    /\ UNCHANGED <<loadedPDF, activeFeature, extractedContext, 
                   draftTLA_File, tlcStatus, globalDictionary>>

(* ----------------------------------------------------------------
 * AI_Generate_TLA_Draft(generatedCode)
 *
 * Source (section Project Overview):
 * "The tool will use GitHub Copilot in Agent Mode to extract the context...
 * and generate the necessary definitions and formulas intended for TLA+
 * specification draft" [cite: 15]
 *)
AI_Generate_TLA_Draft(generatedCode) ==
    /\ agentPrompt # EmptyString
    /\ draftTLA_File' = generatedCode
    /\ tlcStatus' = TLC_Pending
    /\ UNCHANGED <<loadedPDF, activeFeature, extractedContext, 
                   agentPrompt, globalDictionary>>

(* ----------------------------------------------------------------
 * User_Manual_Edit(editedCode)
 *
 * Source (section Project Overview):
 * "Users will be able to manually edit this TLA+ specification draft
 * within the VS Code IDE." [cite: 16]
 *)
User_Manual_Edit(editedCode) ==
    /\ draftTLA_File # EmptyString
    /\ draftTLA_File' = editedCode
    /\ tlcStatus' = TLC_Pending      (* Edits require re-verification *)
    /\ UNCHANGED <<loadedPDF, activeFeature, extractedContext, 
                   agentPrompt, globalDictionary>>

(* ----------------------------------------------------------------
 * Run_TLC_Model_Checker(result)
 *
 * Source (section Project Overview):
 * "The draft and any edits can be iteratively verified with the TLC
 * model checker... AI results are probabilistic, but they can be
 * exhaustively checked across all possible scenarios" [cite: 17, 23]
 *)
Run_TLC_Model_Checker(result) ==
    /\ draftTLA_File # EmptyString
    /\ tlcStatus' = result
    /\ UNCHANGED <<loadedPDF, activeFeature, extractedContext, 
                   agentPrompt, draftTLA_File, globalDictionary>>

(* ----------------------------------------------------------------
 * Update_Global_Dictionary(newTerms)
 *
 * Source (section Project Overview):
 * "Create a dictionary of the VARIABLES and CONSTANTS found in the
 * TLA+ specification. This dictionary will be used as a common global
 * collection" [cite: 19, 20]
 *)
Update_Global_Dictionary(newTerms) ==
    /\ tlcStatus = TLC_Pass          (* Must pass TLC first *)
    /\ globalDictionary' = globalDictionary \cup newTerms
    /\ UNCHANGED <<loadedPDF, activeFeature, extractedContext, 
                   agentPrompt, draftTLA_File, tlcStatus>>

(* ================================================================
 * NEXT-STATE RELATION
 * ================================================================ *)

Next ==
    \/ \E pdf \in STRING : Load_PDF_Specification(pdf)
    \/ \E feat \in Features, ctx \in STRING : Extract_Feature_Context(feat, ctx)
    \/ \E prmpt \in STRING : Generate_AI_Prompt(prmpt)
    \/ \E code \in STRING : AI_Generate_TLA_Draft(code)
    \/ \E edit \in STRING : User_Manual_Edit(edit)
    \/ \E res \in {TLC_Pass, TLC_Fail} : Run_TLC_Model_Checker(res)
    \/ \E terms \in SUBSET STRING : Update_Global_Dictionary(terms)

(* ================================================================
 * INVARIANTS
 * ================================================================ *)

(*
 * INV 1 - TypeOK
 * All state variables have the expected types.
 *)
(* TypeOK is defined above *)

(*
 * INV 2 - PromptRequiresContext
 *
 * The tool cannot construct a prompt for the Agent AI without having
 * first extracted the context from the natural language requirement block.
 *)
PromptRequiresContext ==
    (agentPrompt # EmptyString) => (extractedContext # EmptyString)

(*
 * INV 3 - DictionaryIntegrity
 *
 * The tool shall not extract VARIABLES and CONSTANTS into the global
 * dictionary unless the associated draft TLA+ specification has successfully
 * passed verification by the TLC model checker. [cite: 18, 19]
 *)
DictionaryIntegrity ==
    (globalDictionary # {}) => (tlcStatus = TLC_Pass)

(* ================================================================
 * COMPLETE SPECIFICATION
 * ================================================================ *)

Spec == Init /\ [][Next]_vars

=============================================================================
